baseURL: "https://kavithadataeng.github.io/site/"
languageCode: en-us
title: Kavitha  
theme: PaperMod


permalinks:
  posts: "/:slug"

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    FirstParagraph: >
      Welecome to my personal blog.       
      I am Kavitha, a Data Architect & passionate about Data Engineering. This blog is a collection of my thoughts, ideas, and experiences. 
    SecondParagraph: >
    
    Title: Kavitha 
   

  socialIcons:
    - name: email
      url: "mailto:kavithadataeng@gmail.com"
    - name: github
      url: "https://github.com/kavithadataeng"
    - name: twitter
      url: "https://twitter.com/kavithadataeng"
 

menu:
  main:
    - name: Posts
      pageRef: /posts/
      weight: 2  
    - identifier: GitHub
      name: GitHub
      url: "https://github.com/kavithadataeng"
      weight: 5
